name: Build and test (ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build kernel.
      run: make -j$(nproc --all)
      
  clean:
  
    runs-on: ubuntu-latest
    steps:
      - run: make clean
